[package]
name = "launcher"
version = "0.1.0"
authors = ["bender"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.8.1"
gdk = "0.12.1"
fuzzy-matcher = "0.3.4"
xdg = "2.2.0"
